### ISSUE TITLE
npm run dev failed with initiall start proyect

### ISSUE THREAD

**Issue by pikMR** [CrystallizeAPI/crystallize-nextjs-boilerplate#54]
**maybe need another reference?**

\pages\_document.js: transform-react-jsx: pragma has been set but pragmaFrag has not been set

    at transformFile.next (<anonymous>)
    at run.next (<anonymous>)
    at transform.next (<anonymous>)

**Comment by hakonkrogh** [comment]
Hi @pikMR. Thanks for the feedback.

This looks like a Babel issue which they should have resolved now. 
[https://github.com/zeit/next.js/issues/11230](https://github.com/zeit/next.js/issues/11230)

I just did a fresh install using `npx @crystallize/cli` and that worked. Can you confirm?

**Comment by pikMR** [comment]
> Hi @pikMR. Thanks for the feedback.
> 
> This looks like a Babel issue which they should have resolved now.
> [zeit/next.js#11230](https://github.com/zeit/next.js/issues/11230)
> 
> I just did a fresh install using `npx @crystallize/cli` and that worked. Can you confirm?

Hi @hakonkrogh , i used "npx @crystallize/cli mynameproyect" before
i selected  bearshop,next.js,zeit,stripe and now in new proyect work fine... 
for fix this problem in my last proyect i comment throws exceptions :'(

**Comment by hakonkrogh** [comment]
Great that it works with a fresh install now.

For your existing project you should be able to fix it by running `npm update` to get the latest patches.
