### ISSUE TITLE
The attributes for variants are not removed in the UI, if they are not present in one of the variants

### ISSUE THREAD

**Issue by stunjiturner** [CrystallizeAPI/crystallize-nextjs-boilerplate#70]
Example. PIM

variants created.
Bue XL
Blue L
Blue S
Red XL

the ui in the boilerplate, will generate variants for the sizes XL, L ,S, which works correctly, but when red is selected, L,S size attributes are still displayed, which does not exist for red. this causes and error in the boilerplate.

**Comment by hakonkrogh** [comment]
Hi @stunjiturner and thank you for this bug report. Fixed in `main` now
