### ISSUE TITLE
BUG: i18 currency fail on hydrate

### ISSUE THREAD

**Issue by TommySorensen** [CrystallizeAPI/crystallize-nextjs-boilerplate#94]
When using other languages then `en-US` which is the default in this repo, then the interpolation will make client and server different.

The issue is the function in this file https://github.com/CrystallizeAPI/crystallize-nextjs-boilerplate/blob/main/src/lib/i18n.js is using the `Intl.NumberFormat` to format the corrency. The function is never run on server side but only client. So on server site the currency is not added, meaning price is `400` where on client it will be `400,00 kr` in DKK currency.

I also tried with EUR, but that also fails.
![image](https://user-images.githubusercontent.com/4134473/114770732-0c1a2180-9d6c-11eb-8c56-8c64c3f0c9d9.png)

To reproduce just run the boilerplate on localhost with locale en-US and da-DK, and eur and dkk as currency.

I reached out too @hakonkrogh on [slach](https://crystallizecommunity.slack.com/archives/C01DP46Q410/p1618172658158100) which mentioned that on vercel builds with node version below v. 14 this will help https://vercel.com/support/articles/how-can-i-use-full-icu-with-vercel
I am running v. 14, so it was not the fix for this issue.

**Comment by hakonkrogh** [comment]
This happens with all locales form then looks of it. Might be an issue with next-i18next not applying the interpolation format function.

I filed a bug report with that library just now: https://github.com/isaachinman/next-i18next/issues/1145.

**Comment by hakonkrogh** [comment]
Fixed now in the latest commit: https://github.com/CrystallizeAPI/crystallize-nextjs-boilerplate/commit/1135ac465fc0c3a55f277d4e05ea7c688748a925

Thank you for drawing attention to the issue @TommySorensen
